dist: trusty
sudo: required

notifications:
  email:
    on_success: never
    on_failure: always

language: java

jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

services:
  - mysql

before_script:
 - mysql -u root -e "UPDATE mysql.user SET password = PASSWORD('root') WHERE user = 'root'; FLUSH PRIVILEGES;"
 - echo "Set MySQL root password.."
 - mysql -u travis -e "CREATE DATABASE tirociniosmart;"
 - echo "TirocinioSmart schema created.."
 - cd webapp
 - echo "Moved to webapp root.."
 - chmod +x mvnw
 - echo "Set maven wrapper execution permission.."

script: ./mvnw clean install spring-boot:repackage